name: responsive_nav_barx
description: "BottomNavigationBar for mobile, NavigationRail for wide screens and TabBar for widerrrr screens"
version: 1.0.1
repository: https://github.com/Flexxxlab/responsive_nav_bar
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.10.3
  flutter: ">=2.51.1"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true